<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use \Carbon\Carbon;

class AddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('addresses')->insert([
            [
                'street' => '123 Oak Street',
                'city' => 'Springfield',
                'state' => 'Illinois',
                'country' => 'USA',
                'zip' => 62704,
                'user_id' => 94791,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Maple Avenue',
                'city' => 'Riverside',
                'state' => 'California',
                'country' => 'USA',
                'zip' => 92501,
                'user_id' => 94791,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Willow Street',
                'city' => 'Denver',
                'state' => 'Colorado',
                'country' => 'USA',
                'zip' => 80202,
                'user_id' => 94792,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Vineyard Lane',
                'city' => 'Austin',
                'state' => 'Texas',
                'country' => 'USA',
                'zip' => 78701,
                'user_id' => 94792,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Redwood Drive',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'country' => 'USA',
                'zip' => 60601,
                'user_id' => 94793,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Elm Street',
                'city' => 'New York',
                'state' => 'New York',
                'country' => 'USA',
                'zip' => 10001,
                'user_id' => 94793,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'street' => '789 Cedar Avenue',
                'city' => 'Seattle',
                'state' => 'Washington',
                'country' => 'USA',
                'zip' => 98101,
                'user_id' => 94794,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Pine Street',
                'city' => 'Portland',
                'state' => 'Oregon',
                'country' => 'USA',
                'zip' => 97201,
                'user_id' => 94794,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'street' => '234 Birch Lane',
                'city' => 'Miami',
                'state' => 'Florida',
                'country' => 'USA',
                'zip' => 33101,
                'user_id' => 94795,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Pine Street',
                'city' => 'Orlando',
                'state' => 'Florida',
                'country' => 'USA',
                'zip' => 32801,
                'user_id' => 94796,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Elm Avenue',
                'city' => 'Los Angeles',
                'state' => 'California',
                'country' => 'USA',
                'zip' => 90001,
                'user_id' => 94796,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Oak Street',
                'city' => 'Dallas',
                'state' => 'Texas',
                'country' => 'USA',
                'zip' => 75201,
                'user_id' => 94797,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Maple Avenue',
                'city' => 'Houston',
                'state' => 'Texas',
                'country' => 'USA',
                'zip' => 77001,
                'user_id' => 94797,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Willow Street',
                'city' => 'San Francisco',
                'state' => 'California',
                'country' => 'USA',
                'zip' => 94101,
                'user_id' => 94798,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Vineyard Lane',
                'city' => 'San Diego',
                'state' => 'California',
                'country' => 'USA',
                'zip' => 92101,
                'user_id' => 94798,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Cedar Drive',
                'city' => 'Las Vegas',
                'state' => 'Nevada',
                'country' => 'USA',
                'zip' => 89101,
                'user_id' => 94799,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Pine Street',
                'city' => 'Phoenix',
                'state' => 'Arizona',
                'country' => 'USA',
                'zip' => 85001,
                'user_id' => 94799,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Elm Avenue',
                'city' => 'Atlanta',
                'state' => 'Georgia',
                'country' => 'USA',
                'zip' => 30301,
                'user_id' => 94800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Oak Street',
                'city' => 'Boston',
                'state' => 'Massachusetts',
                'country' => 'USA',
                'zip' => 12101,
                'user_id' => 94800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Maple Avenue',
                'city' => 'Philadelphia',
                'state' => 'Pennsylvania',
                'country' => 'USA',
                'zip' => 19101,
                'user_id' => 94801,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Willow Street',
                'city' => 'Detroit',
                'state' => 'Michigan',
                'country' => 'USA',
                'zip' => 48201,
                'user_id' => 94801,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Vineyard Lane',
                'city' => 'Minneapolis',
                'state' => 'Minnesota',
                'country' => 'USA',
                'zip' => 55401,
                'user_id' => 94802,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Cedar Drive',
                'city' => 'St. Louis',
                'state' => 'Missouri',
                'country' => 'USA',
                'zip' => 63101,
                'user_id' => 94802,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Pine Street',
                'city' => 'New Orleans',
                'state' => 'Louisiana',
                'country' => 'USA',
                'zip' => 70112,
                'user_id' => 94803,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Elm Avenue',
                'city' => 'Kansas City',
                'state' => 'Missouri',
                'country' => 'USA',
                'zip' => 64101,
                'user_id' => 94803,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Oak Street',
                'city' => 'Salt Lake City',
                'state' => 'Utah',
                'country' => 'USA',
                'zip' => 84101,
                'user_id' => 94804,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Maple Avenue',
                'city' => 'Honolulu',
                'state' => 'Hawaii',
                'country' => 'USA',
                'zip' => 96801,
                'user_id' => 94804,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Willow Street',
                'city' => 'Anchorage',
                'state' => 'Alaska',
                'country' => 'USA',
                'zip' => 99501,
                'user_id' => 94805,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Vineyard Lane',
                'city' => 'Boise',
                'state' => 'Idaho',
                'country' => 'USA',
                'zip' => 83701,
                'user_id' => 94805,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Cedar Drive',
                'city' => 'Tucson',
                'state' => 'Arizona',
                'country' => 'USA',
                'zip' => 85701,
                'user_id' => 94806,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Pine Street',
                'city' => 'Albuquerque',
                'state' => 'New Mexico',
                'country' => 'USA',
                'zip' => 87101,
                'user_id' => 94806,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Elm Avenue',
                'city' => 'Fargo',
                'state' => 'North Dakota',
                'country' => 'USA',
                'zip' => 58102,
                'user_id' => 94807,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Oak Street',
                'city' => 'Sioux Falls',
                'state' => 'South Dakota',
                'country' => 'USA',
                'zip' => 57103,
                'user_id' => 94807,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Maple Avenue',
                'city' => 'Billings',
                'state' => 'Montana',
                'country' => 'USA',
                'zip' => 59101,
                'user_id' => 94808,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Willow Street',
                'city' => 'Helena',
                'state' => 'Montana',
                'country' => 'USA',
                'zip' => 59601,
                'user_id' => 94808,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Vineyard Lane',
                'city' => 'Oklahoma City',
                'state' => 'Oklahoma',
                'country' => 'USA',
                'zip' => 73101,
                'user_id' => 94809,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Cedar Drive',
                'city' => 'Des Moines',
                'state' => 'Iowa',
                'country' => 'USA',
                'zip' => 50301,
                'user_id' => 94809,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'street' => '123 Elm Street',
                'city' => 'Charlotte',
                'state' => 'North Carolina',
                'country' => 'USA',
                'zip' => 28202,
                'user_id' => 94810,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Oak Avenue',
                'city' => 'Indianapolis',
                'state' => 'Indiana',
                'country' => 'USA',
                'zip' => 46201,
                'user_id' => 94811,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Maple Lane',
                'city' => 'Columbus',
                'state' => 'Ohio',
                'country' => 'USA',
                'zip' => 43201,
                'user_id' => 94812,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Cedar Drive',
                'city' => 'Nashville',
                'state' => 'Tennessee',
                'country' => 'USA',
                'zip' => 37201,
                'user_id' => 94813,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Pine Street',
                'city' => 'Memphis',
                'state' => 'Tennessee',
                'country' => 'USA',
                'zip' => 38101,
                'user_id' => 94814,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Vineyard Lane',
                'city' => 'Louisville',
                'state' => 'Kentucky',
                'country' => 'USA',
                'zip' => 40201,
                'user_id' => 94815,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Cedar Drive',
                'city' => 'Milwaukee',
                'state' => 'Wisconsin',
                'country' => 'USA',
                'zip' => 53201,
                'user_id' => 94816,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Elm Street',
                'city' => 'Kansas City',
                'state' => 'Kansas',
                'country' => 'USA',
                'zip' => 66101,
                'user_id' => 94817,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Oak Avenue',
                'city' => 'Omaha',
                'state' => 'Nebraska',
                'country' => 'USA',
                'zip' => 68101,
                'user_id' => 94818,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Maple Lane',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'country' => 'USA',
                'zip' => 74101,
                'user_id' => 94819,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Cedar Drive',
                'city' => 'Wichita',
                'state' => 'Kansas',
                'country' => 'USA',
                'zip' => 67201,
                'user_id' => 94820,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Pine Street',
                'city' => 'Little Rock',
                'state' => 'Arkansas',
                'country' => 'USA',
                'zip' => 72201,
                'user_id' => 94821,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Vineyard Lane',
                'city' => 'Birmingham',
                'state' => 'Alabama',
                'country' => 'USA',
                'zip' => 35201,
                'user_id' => 94822,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Cedar Drive',
                'city' => 'Jackson',
                'state' => 'Mississippi',
                'country' => 'USA',
                'zip' => 39201,
                'user_id' => 94823,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Elm Street',
                'city' => 'Baton Rouge',
                'state' => 'Louisiana',
                'country' => 'USA',
                'zip' => 70801,
                'user_id' => 94824,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Oak Avenue',
                'city' => 'Columbia',
                'state' => 'South Carolina',
                'country' => 'USA',
                'zip' => 29201,
                'user_id' => 94825,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Maple Lane',
                'city' => 'Savannah',
                'state' => 'Georgia',
                'country' => 'USA',
                'zip' => 31401,
                'user_id' => 94826,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Cedar Drive',
                'city' => 'Charleston',
                'state' => 'South Carolina',
                'country' => 'USA',
                'zip' => 29401,
                'user_id' => 94827,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Pine Street',
                'city' => 'Richmond',
                'state' => 'Virginia',
                'country' => 'USA',
                'zip' => 23218,
                'user_id' => 94828,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Vineyard Lane',
                'city' => 'Annapolis',
                'state' => 'Maryland',
                'country' => 'USA',
                'zip' => 21401,
                'user_id' => 94829,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Cedar Drive',
                'city' => 'Hartford',
                'state' => 'Connecticut',
                'country' => 'USA',
                'zip' => 16101,
                'user_id' => 94830,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Elm Street',
                'city' => 'Dover',
                'state' => 'Delaware',
                'country' => 'USA',
                'zip' => 19901,
                'user_id' => 94831,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Oak Avenue',
                'city' => 'Augusta',
                'state' => 'Maine',
                'country' => 'USA',
                'zip' => 14330,
                'user_id' => 94832,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Maple Lane',
                'city' => 'Concord',
                'state' => 'New Hampshire',
                'country' => 'USA',
                'zip' => 13301,
                'user_id' => 94833,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Cedar Drive',
                'city' => 'Montpelier',
                'state' => 'Vermont',
                'country' => 'USA',
                'zip' => 15602,
                'user_id' => 94834,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '234 Pine Street',
                'city' => 'Providence',
                'state' => 'Rhode Island',
                'country' => 'USA',
                'zip' => 12901,
                'user_id' => 94835,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '567 Vineyard Lane',
                'city' => 'Burlington',
                'state' => 'Vermont',
                'country' => 'USA',
                'zip' => 15401,
                'user_id' => 94836,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '890 Cedar Drive',
                'city' => 'Harrisburg',
                'state' => 'Pennsylvania',
                'country' => 'USA',
                'zip' => 17101,
                'user_id' => 94837,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '123 Elm Street',
                'city' => 'Albany',
                'state' => 'New York',
                'country' => 'USA',
                'zip' => 12201,
                'user_id' => 94838,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '456 Oak Avenue',
                'city' => 'Hartford',
                'state' => 'Connecticut',
                'country' => 'USA',
                'zip' => 1101,
                'user_id' => 94839,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '789 Maple Lane',
                'city' => 'Trenton',
                'state' => 'New Jersey',
                'country' => 'USA',
                'zip' => 18601,
                'user_id' => 94840,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'street' => '901 Cedar Drive',
                'city' => 'Dover',
                'state' => 'Delaware',
                'country' => 'USA',
                'zip' => 19901,
                'user_id' => 94841,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
