<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use \Carbon\Carbon;

class BillingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('billings')->insert([
            [
                'name' => 'John Doe',
                'email' => 'john.doe@example.com',
                'phone' => '123-456-7890',
                'address' => '1234 Main Street',
                'country' => 'USA',
                'city' => 'Anytown',
                'state' => 'CA',
                'user_id' => 94791, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jane Smith',
                'email' => 'jane.smith@example.com',
                'phone' => '987-654-3210',
                'address' => '5678 Elm Street',
                'country' => 'USA',
                'city' => 'Othertown',
                'state' => 'NY',
                'user_id' => 94791,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Alice Johnson',
                'email' => 'alice.johnson@example.com',
                'phone' => '111-222-3333',
                'address' => '123 Oak Street',
                'country' => 'USA',
                'city' => 'Springfield',
                'state' => 'IL',
                'user_id' => 94792, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bob Thompson',
                'email' => 'bob.thompson@example.com',
                'phone' => '444-555-6666',
                'address' => '456 Maple Avenue',
                'country' => 'USA',
                'city' => 'Riverside',
                'state' => 'CA',
                'user_id' => 94792,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Carol Garcia',
                'email' => 'carol.garcia@example.com',
                'phone' => '777-888-9999',
                'address' => '789 Willow Street',
                'country' => 'USA',
                'city' => 'Seattle',
                'state' => 'WA',
                'user_id' => 94793, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'David Martinez',
                'email' => 'david.martinez@example.com',
                'phone' => '123-456-7890',
                'address' => '567 Willow Street',
                'country' => 'USA',
                'city' => 'Denver',
                'state' => 'CO',
                'user_id' => 94793,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Eva Hernandez',
                'email' => 'eva.hernandez@example.com',
                'phone' => '987-654-3210',
                'address' => '123 Redwood Drive',
                'country' => 'USA',
                'city' => 'Chicago',
                'state' => 'IL',
                'user_id' => 94794,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Frank Wilson',
                'email' => 'frank.wilson@example.com',
                'phone' => '555-444-3333',
                'address' => '456 Elm Street',
                'country' => 'USA',
                'city' => 'New York',
                'state' => 'NY',
                'user_id' => 94794,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Grace Lee',
                'email' => 'grace.lee@example.com',
                'phone' => '999-888-7777',
                'address' => '890 Vineyard Lane',
                'country' => 'USA',
                'city' => 'Austin',
                'state' => 'TX',
                'user_id' => 94795, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Henry Nguyen',
                'email' => 'henry.nguyen@example.com',
                'phone' => '222-333-4444',
                'address' => '123 Oak Street',
                'country' => 'USA',
                'city' => 'Dallas',
                'state' => 'TX',
                'user_id' => 94795,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isabella Kim',
                'email' => 'isabella.kim@example.com',
                'phone' => '666-777-8888',
                'address' => '456 Maple Avenue',
                'country' => 'USA',
                'city' => 'Houston',
                'state' => 'TX',
                'user_id' => 94796, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jackie Singh',
                'email' => 'jackie.singh@example.com',
                'phone' => '333-444-5555',
                'address' => '567 Willow Street',
                'country' => 'USA',
                'city' => 'San Francisco',
                'state' => 'CA',
                'user_id' => 94796,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kevin Patel',
                'email' => 'kevin.patel@example.com',
                'phone' => '777-888-9999',
                'address' => '789 Cedar Avenue',
                'country' => 'USA',
                'city' => 'Seattle',
                'state' => 'WA',
                'user_id' => 94797, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Linda Brown',
                'email' => 'linda.brown@example.com',
                'phone' => '111-222-3333',
                'address' => '901 Pine Street',
                'country' => 'USA',
                'city' => 'Portland',
                'state' => 'OR',
                'user_id' => 94797,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Michael Wilson',
                'email' => 'michael.wilson@example.com',
                'phone' => '222-333-4444',
                'address' => '234 Cedar Drive',
                'country' => 'USA',
                'city' => 'Tucson',
                'state' => 'AZ',
                'user_id' => 94798, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nancy Garcia',
                'email' => 'nancy.garcia@example.com',
                'phone' => '555-666-7777',
                'address' => '567 Pine Street',
                'country' => 'USA',
                'city' => 'Albuquerque',
                'state' => 'NM',
                'user_id' => 94798,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Oliver Martinez',
                'email' => 'oliver.martinez@example.com',
                'phone' => '888-999-0000',
                'address' => '890 Elm Avenue',
                'country' => 'USA',
                'city' => 'Fargo',
                'state' => 'ND',
                'user_id' => 94799, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Patricia Lopez',
                'email' => 'patricia.lopez@example.com',
                'phone' => '111-222-3333',
                'address' => '123 Oak Street',
                'country' => 'USA',
                'city' => 'Sioux Falls',
                'state' => 'SD',
                'user_id' => 94799,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Quincy Adams',
                'email' => 'quincy.adams@example.com',
                'phone' => '444-555-6666',
                'address' => '456 Maple Avenue',
                'country' => 'USA',
                'city' => 'Billings',
                'state' => 'MT',
                'user_id' => 94800, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rachel Thompson',
                'email' => 'rachel.thompson@example.com',
                'phone' => '777-888-9999',
                'address' => '789 Willow Street',
                'country' => 'USA',
                'city' => 'Helena',
                'state' => 'MT',
                'user_id' => 94800,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Samantha Harris',
                'email' => 'samantha.harris@example.com',
                'phone' => '333-444-5555',
                'address' => '901 Vineyard Lane',
                'country' => 'USA',
                'city' => 'Boise',
                'state' => 'ID',
                'user_id' => 94801, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Thomas Adams',
                'email' => 'thomas.adams@example.com',
                'phone' => '666-777-8888',
                'address' => '234 Cedar Drive',
                'country' => 'USA',
                'city' => 'Des Moines',
                'state' => 'IA',
                'user_id' => 94802,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ursula Bell',
                'email' => 'ursula.bell@example.com',
                'phone' => '999-888-7777',
                'address' => '567 Pine Street',
                'country' => 'USA',
                'city' => 'Columbia',
                'state' => 'SC',
                'user_id' => 94803, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Victor Clark',
                'email' => 'victor.clark@example.com',
                'phone' => '222-333-4444',
                'address' => '890 Cedar Drive',
                'country' => 'USA',
                'city' => 'Savannah',
                'state' => 'GA',
                'user_id' => 94804,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wendy Davis',
                'email' => 'wendy.davis@example.com',
                'phone' => '555-666-7777',
                'address' => '123 Elm Street',
                'country' => 'USA',
                'city' => 'Charleston',
                'state' => 'SC',
                'user_id' => 94805, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Xavier Evans',
                'email' => 'xavier.evans@example.com',
                'phone' => '777-888-9999',
                'address' => '456 Oak Avenue',
                'country' => 'USA',
                'city' => 'Richmond',
                'state' => 'VA',
                'user_id' => 94806, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yolanda Flores',
                'email' => 'yolanda.flores@example.com',
                'phone' => '222-333-4444',
                'address' => '789 Maple Lane',
                'country' => 'USA',
                'city' => 'Honolulu',
                'state' => 'HI',
                'user_id' => 94807,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Zachary Gomez',
                'email' => 'zachary.gomez@example.com',
                'phone' => '555-666-7777',
                'address' => '901 Cedar Drive',
                'country' => 'USA',
                'city' => 'Juneau',
                'state' => 'AK',
                'user_id' => 94808, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Abigail Hernandez',
                'email' => 'abigail.hernandez@example.com',
                'phone' => '888-999-0000',
                'address' => '234 Pine Street',
                'country' => 'USA',
                'city' => 'Annapolis',
                'state' => 'MD',
                'user_id' => 94809,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Benjamin Ingram',
                'email' => 'benjamin.ingram@example.com',
                'phone' => '333-444-5555',
                'address' => '567 Vineyard Lane',
                'country' => 'USA',
                'city' => 'Boise',
                'state' => 'ID',
                'user_id' => 94810, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Cameron Johnson',
                'email' => 'cameron.johnson@example.com',
                'phone' => '777-888-9999',
                'address' => '123 Oak Street',
                'country' => 'USA',
                'city' => 'Springfield',
                'state' => 'IL',
                'user_id' => 94811, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Diana Kim',
                'email' => 'diana.kim@example.com',
                'phone' => '222-333-4444',
                'address' => '456 Maple Avenue',
                'country' => 'USA',
                'city' => 'Riverside',
                'state' => 'CA',
                'user_id' => 94812,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Edward Lee',
                'email' => 'edward.lee@example.com',
                'phone' => '555-666-7777',
                'address' => '789 Willow Street',
                'country' => 'USA',
                'city' => 'Seattle',
                'state' => 'WA',
                'user_id' => 94813, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fiona Martinez',
                'email' => 'fiona.martinez@example.com',
                'phone' => '888-999-0000',
                'address' => '901 Pine Street',
                'country' => 'USA',
                'city' => 'Portland',
                'state' => 'OR',
                'user_id' => 94814,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'George Nguyen',
                'email' => 'george.nguyen@example.com',
                'phone' => '333-444-5555',
                'address' => '234 Cedar Drive',
                'country' => 'USA',
                'city' => 'Boise',
                'state' => 'ID',
                'user_id' => 94815, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Alice Smith',
                'email' => 'alice.smith@example.com',
                'phone' => '123-456-7890',
                'address' => '1234 Main Street',
                'country' => 'USA',
                'city' => 'Anytown',
                'state' => 'CA',
                'user_id' => 94816, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bob Johnson',
                'email' => 'bob.johnson@example.com',
                'phone' => '987-654-3210',
                'address' => '5678 Elm Street',
                'country' => 'USA',
                'city' => 'Othertown',
                'state' => 'NY',
                'user_id' => 94817,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Carol Williams',
                'email' => 'carol.williams@example.com',
                'phone' => '111-222-3333',
                'address' => '901 Vineyard Lane',
                'country' => 'USA',
                'city' => 'Annapolis',
                'state' => 'MD',
                'user_id' => 94818, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'David Brown',
                'email' => 'david.brown@example.com',
                'phone' => '444-555-6666',
                'address' => '234 Cedar Drive',
                'country' => 'USA',
                'city' => 'Montpelier',
                'state' => 'VT',
                'user_id' => 94819,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Emma Jones',
                'email' => 'emma.jones@example.com',
                'phone' => '777-888-9999',
                'address' => '567 Pine Street',
                'country' => 'USA',
                'city' => 'Burlington',
                'state' => 'VT',
                'user_id' => 94820, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Frank Rodriguez',
                'email' => 'frank.rodriguez@example.com',
                'phone' => '333-444-5555',
                'address' => '890 Cedar Drive',
                'country' => 'USA',
                'city' => 'Hartford',
                'state' => 'CT',
                'user_id' => 94821, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gina Wilson',
                'email' => 'gina.wilson@example.com',
                'phone' => '666-777-8888',
                'address' => '123 Elm Street',
                'country' => 'USA',
                'city' => 'Dover',
                'state' => 'DE',
                'user_id' => 94822,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Henry Thomas',
                'email' => 'henry.thomas@example.com',
                'phone' => '999-888-7777',
                'address' => '456 Oak Avenue',
                'country' => 'USA',
                'city' => 'Augusta',
                'state' => 'ME',
                'user_id' => 94823, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ivy Martinez',
                'email' => 'ivy.martinez@example.com',
                'phone' => '222-333-4444',
                'address' => '789 Maple Lane',
                'country' => 'USA',
                'city' => 'Concord',
                'state' => 'NH',
                'user_id' => 94824,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jack Smith',
                'email' => 'jack.smith@example.com',
                'phone' => '555-666-7777',
                'address' => '901 Cedar Drive',
                'country' => 'USA',
                'city' => 'Montpelier',
                'state' => 'VT',
                'user_id' => 94825, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Katherine Brown',
                'email' => 'katherine.brown@example.com',
                'phone' => '777-888-9999',
                'address' => '123 Oak Street',
                'country' => 'USA',
                'city' => 'Providence',
                'state' => 'RI',
                'user_id' => 94826, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Liam Davis',
                'email' => 'liam.davis@example.com',
                'phone' => '222-333-4444',
                'address' => '456 Maple Avenue',
                'country' => 'USA',
                'city' => 'Columbia',
                'state' => 'SC',
                'user_id' => 94827,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Megan Garcia',
                'email' => 'megan.garcia@example.com',
                'phone' => '555-666-7777',
                'address' => '789 Willow Street',
                'country' => 'USA',
                'city' => 'Pierre',
                'state' => 'SD',
                'user_id' => 94828, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Noah Hernandez',
                'email' => 'noah.hernandez@example.com',
                'phone' => '888-999-0000',
                'address' => '901 Pine Street',
                'country' => 'USA',
                'city' => 'Nashville',
                'state' => 'TN',
                'user_id' => 94829,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Olivia Jackson',
                'email' => 'olivia.jackson@example.com',
                'phone' => '333-444-5555',
                'address' => '234 Cedar Drive',
                'country' => 'USA',
                'city' => 'Austin',
                'state' => 'TX',
                'user_id' => 94830, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Peter Johnson',
                'email' => 'peter.johnson@example.com',
                'phone' => '777-888-9999',
                'address' => '567 Pine Street',
                'country' => 'USA',
                'city' => 'Salt Lake City',
                'state' => 'UT',
                'user_id' => 94831, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Quinn Martinez',
                'email' => 'quinn.martinez@example.com',
                'phone' => '222-333-4444',
                'address' => '789 Cedar Avenue',
                'country' => 'USA',
                'city' => 'Montpelier',
                'state' => 'VT',
                'user_id' => 94832,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rachel Nguyen',
                'email' => 'rachel.nguyen@example.com',
                'phone' => '555-666-7777',
                'address' => '901 Vineyard Lane',
                'country' => 'USA',
                'city' => 'Richmond',
                'state' => 'VA',
                'user_id' => 94833, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Samuel Patel',
                'email' => 'samuel.patel@example.com',
                'phone' => '888-999-0000',
                'address' => '123 Elm Street',
                'country' => 'USA',
                'city' => 'Montpelier',
                'state' => 'VT',
                'user_id' => 94834,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Taylor Ramirez',
                'email' => 'taylor.ramirez@example.com',
                'phone' => '333-444-5555',
                'address' => '456 Oak Avenue',
                'country' => 'USA',
                'city' => 'Olympia',
                'state' => 'WA',
                'user_id' => 94835, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'name' => 'Uma Singh',
                'email' => 'uma.singh@example.com',
                'phone' => '777-888-9999',
                'address' => '789 Maple Lane',
                'country' => 'USA',
                'city' => 'Charleston',
                'state' => 'WV',
                'user_id' => 94836, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Victor Thompson',
                'email' => 'victor.thompson@example.com',
                'phone' => '222-333-4444',
                'address' => '901 Cedar Drive',
                'country' => 'USA',
                'city' => 'Madison',
                'state' => 'WI',
                'user_id' => 94837,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wendy White',
                'email' => 'wendy.white@example.com',
                'phone' => '555-666-7777',
                'address' => '123 Oak Street',
                'country' => 'USA',
                'city' => 'Cheyenne',
                'state' => 'WY',
                'user_id' => 94838, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Xavier Young',
                'email' => 'xavier.young@example.com',
                'phone' => '888-999-0000',
                'address' => '456 Maple Avenue',
                'country' => 'USA',
                'city' => 'Casper',
                'state' => 'WY',
                'user_id' => 94839,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yolanda Zimmerman',
                'email' => 'yolanda.zimmerman@example.com',
                'phone' => '333-444-5555',
                'address' => '789 Willow Street',
                'country' => 'USA',
                'city' => 'Laramie',
                'state' => 'WY',
                'user_id' => 94840, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'name' => 'Zara Adams',
                'email' => 'zara.adams@example.com',
                'phone' => '777-888-9999',
                'address' => '901 Vineyard Lane',
                'country' => 'USA',
                'city' => 'Cheyenne',
                'state' => 'WY',
                'user_id' => 94841, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
