<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use \Carbon\Carbon;

class CardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cards')->insert([
            [
                'number' => '4242 4242 4242 4242', 
                'expiration_date' => '2030-12-01',
                'cvc' => 123,
                'holder' => 'John Doe',
                'user_id' => 94791, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4000 0566 5566 5556', 
                'expiration_date' => '2030-12-01',
                'cvc' => 456,
                'holder' => 'Jane Smith',
                'user_id' => 94791, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'number' => '5555 5555 5555 5555', 
                'expiration_date' => '2031-01-01',
                'cvc' => 456,
                'holder' => 'Jane Smith',
                'user_id' => 94792, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3782 822463 10005', 
                'expiration_date' => '2031-02-01',
                'cvc' => 789,
                'holder' => 'David Johnson',
                'user_id' => 94793, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'number' => '4111 1111 1111 1111', 
                'expiration_date' => '2030-11-01',
                'cvc' => 234,
                'holder' => 'Emily Brown',
                'user_id' => 94794, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5105 1051 0510 5100', 
                'expiration_date' => '2031-03-01',
                'cvc' => 567,
                'holder' => 'Michael Wilson',
                'user_id' => 94795, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3714 496353 98431', 
                'expiration_date' => '2031-04-01',
                'cvc' => 890,
                'holder' => 'Olivia Jones',
                'user_id' => 94796, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'number' => '6011 6011 6011 6611', 
                'expiration_date' => '2030-10-01',
                'cvc' => 111,
                'holder' => 'William Garcia',
                'user_id' => 94797, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3566 0020 2036 0505', 
                'expiration_date' => '2031-05-01',
                'cvc' => 222,
                'holder' => 'Sophia Martinez',
                'user_id' => 94798, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6612', 
                'expiration_date' => '2031-06-01',
                'cvc' => 333,
                'holder' => 'James Lee',
                'user_id' => 94799, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'number' => '5555 5555 5555 5555', 
                'expiration_date' => '2030-07-01',
                'cvc' => 444,
                'holder' => 'Emma Rodriguez',
                'user_id' => 94800, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4111 1111 1111 1111', 
                'expiration_date' => '2031-08-01',
                'cvc' => 555,
                'holder' => 'Daniel Hernandez',
                'user_id' => 94801, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5105 1051 0510 5100', 
                'expiration_date' => '2030-09-01',
                'cvc' => 666,
                'holder' => 'Isabella Nguyen',
                'user_id' => 94802, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3714 496353 98431', 
                'expiration_date' => '2031-10-01',
                'cvc' => 777,
                'holder' => 'Ethan Kim',
                'user_id' => 94803, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6611', 
                'expiration_date' => '2030-11-01',
                'cvc' => 888,
                'holder' => 'Ava Patel',
                'user_id' => 94804, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3566 0020 2036 0505', 
                'expiration_date' => '2031-12-01',
                'cvc' => 999,
                'holder' => 'Liam Smith',
                'user_id' => 94805, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6612', 
                'expiration_date' => '2032-01-01',
                'cvc' => 111,
                'holder' => 'Mia Thompson',
                'user_id' => 94806, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5555 5555 5555 5555', 
                'expiration_date' => '2032-02-01',
                'cvc' => 222,
                'holder' => 'Noah Garcia',
                'user_id' => 94807, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4111 1111 1111 1111', 
                'expiration_date' => '2032-03-01',
                'cvc' => 333,
                'holder' => 'Sophia Hernandez',
                'user_id' => 94808, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5105 1051 0510 5100', 
                'expiration_date' => '2032-04-01',
                'cvc' => 444,
                'holder' => 'Jacob Martinez',
                'user_id' => 94809, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'number' => '3714 496353 98431', 
                'expiration_date' => '2032-05-01',
                'cvc' => 555,
                'holder' => 'Emily Johnson',
                'user_id' => 94810, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6611', 
                'expiration_date' => '2032-06-01',
                'cvc' => 666,
                'holder' => 'Michael Brown',
                'user_id' => 94811, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3566 0020 2036 0505', 
                'expiration_date' => '2032-07-01',
                'cvc' => 777,
                'holder' => 'Emma Garcia',
                'user_id' => 94812, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6612', 
                'expiration_date' => '2032-08-01',
                'cvc' => 888,
                'holder' => 'William Wilson',
                'user_id' => 94813, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5555 5555 5555 5555', 
                'expiration_date' => '2032-09-01',
                'cvc' => 999,
                'holder' => 'Olivia Martinez',
                'user_id' => 94814, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4111 1111 1111 1111', 
                'expiration_date' => '2032-10-01',
                'cvc' => 111,
                'holder' => 'James Lee',
                'user_id' => 94815, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5105 1051 0510 5100', 
                'expiration_date' => '2032-11-01',
                'cvc' => 222,
                'holder' => 'Ava Lee',
                'user_id' => 94816, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3714 496353 98431', 
                'expiration_date' => '2032-12-01',
                'cvc' => 333,
                'holder' => 'Ethan Lee',
                'user_id' => 94817, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6611', 
                'expiration_date' => '2033-01-01',
                'cvc' => 444,
                'holder' => 'Mia Lee',
                'user_id' => 94818, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3566 0020 2036 0505', 
                'expiration_date' => '2033-02-01',
                'cvc' => 555,
                'holder' => 'Liam Lee',
                'user_id' => 94819, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'number' => '6011 6011 6011 6612', 
                'expiration_date' => '2033-03-01',
                'cvc' => 666,
                'holder' => 'Sophia Brown',
                'user_id' => 94820, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5555 5555 5555 5555', 
                'expiration_date' => '2033-04-01',
                'cvc' => 777,
                'holder' => 'Noah Garcia',
                'user_id' => 94821, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4111 1111 1111 1111', 
                'expiration_date' => '2033-05-01',
                'cvc' => 888,
                'holder' => 'Ava Martinez',
                'user_id' => 94822, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5105 1051 0510 5100', 
                'expiration_date' => '2033-06-01',
                'cvc' => 999,
                'holder' => 'Ethan Johnson',
                'user_id' => 94823, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3714 496353 98431', 
                'expiration_date' => '2033-07-01',
                'cvc' => 111,
                'holder' => 'Mia Thompson',
                'user_id' => 94824, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6611', 
                'expiration_date' => '2033-08-01',
                'cvc' => 222,
                'holder' => 'Liam Wilson',
                'user_id' => 94825, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3566 0020 2036 0505', 
                'expiration_date' => '2033-09-01',
                'cvc' => 333,
                'holder' => 'Olivia Garcia',
                'user_id' => 94826, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6612', 
                'expiration_date' => '2033-10-01',
                'cvc' => 444,
                'holder' => 'William Hernandez',
                'user_id' => 94827, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5555 5555 5555 5555', 
                'expiration_date' => '2033-11-01',
                'cvc' => 555,
                'holder' => 'Sophia Lee',
                'user_id' => 94828, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4111 1111 1111 1111', 
                'expiration_date' => '2033-12-01',
                'cvc' => 666,
                'holder' => 'Ethan Smith',
                'user_id' => 94829, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'number' => '5105 1051 0510 5100', 
                'expiration_date' => '2034-01-01',
                'cvc' => 777,
                'holder' => 'Emma Martinez',
                'user_id' => 94830, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3714 496353 98431', 
                'expiration_date' => '2034-02-01',
                'cvc' => 888,
                'holder' => 'Noah Johnson',
                'user_id' => 94831, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6611', 
                'expiration_date' => '2034-03-01',
                'cvc' => 999,
                'holder' => 'Olivia Lee',
                'user_id' => 94832, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3566 0020 2036 0505', 
                'expiration_date' => '2034-04-01',
                'cvc' => 111,
                'holder' => 'William Brown',
                'user_id' => 94833, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6612', 
                'expiration_date' => '2034-05-01',
                'cvc' => 222,
                'holder' => 'Sophia Smith',
                'user_id' => 94834, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5555 5555 5555 5555', 
                'expiration_date' => '2034-06-01',
                'cvc' => 333,
                'holder' => 'Liam Garcia',
                'user_id' => 94835, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '4111 1111 1111 1111', 
                'expiration_date' => '2034-07-01',
                'cvc' => 444,
                'holder' => 'Emma Martinez',
                'user_id' => 94836, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '5105 1051 0510 5100', 
                'expiration_date' => '2034-08-01',
                'cvc' => 555,
                'holder' => 'Noah Johnson',
                'user_id' => 94837, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '3714 496353 98431', 
                'expiration_date' => '2034-09-01',
                'cvc' => 666,
                'holder' => 'Olivia Lee',
                'user_id' => 94838, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6611', 
                'expiration_date' => '2034-10-01',
                'cvc' => 777,
                'holder' => 'William Brown',
                'user_id' => 94839, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'number' => '3566 0020 2036 0505', 
                'expiration_date' => '2034-11-01',
                'cvc' => 888,
                'holder' => 'Sophia Smith',
                'user_id' => 94840, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'number' => '6011 6011 6011 6612', 
                'expiration_date' => '2034-12-01',
                'cvc' => 999,
                'holder' => 'Liam Garcia',
                'user_id' => 94841, 
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
