<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use \Carbon\Carbon;


class PaymentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('payments')->insert([
            [
                'transaction_id' => '23691',
                'user_id' => '94791',
                'amount' => '254.95',
                'payment_method' => 'card',
                'status' => 'refunded',
                'card_id' => '444791',
                'billing_id' => '333911',
                'refunder' => '94791',
                'created_at' => Carbon::create(2024,4, 22,7, 30, 28),
                'updated_at' => Carbon::create(2024,4, 22,7, 37,6),
            ],
            [
                'transaction_id' => '23692',
                'user_id' => '94791',
                'amount' => '204.95',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444791',
                'billing_id' => '333911',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,7, 30, 50),
                'updated_at' => Carbon::create(2024,4, 22,7, 30, 50),
            ],
            [
                'transaction_id' => '23693',
                'user_id' => '94791',
                'amount' => '1639.59',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444791',
                'billing_id' => '333911',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,8,2, 47),
                'updated_at' => Carbon::create(2024,4, 22,8,2, 47),
            ],
            [
                'transaction_id' => '23694',
                'user_id' => '94791',
                'amount' => '799.91',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444791',
                'billing_id' => '333912',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,9, 27, 19),
                'updated_at' => Carbon::create(2024,4, 22,9, 27, 19),
            ],
            [
                'transaction_id' => '23695',
                'user_id' => '94792',
                'amount' => '125.75',
                'payment_method' => 'card',
                'status' => 'pending',
                'card_id' => '444791',
                'billing_id' => '333914',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 21,9, 52, 56),
                'updated_at' => Carbon::create(2024,4, 22,9, 52, 56),
            ],
            [
                'transaction_id' => '23696',
                'user_id' => '94795',
                'amount' => '95.50',
                'payment_method' => 'cash',
                'status' => 'pending',
                'card_id' => null,
                'billing_id' => '333934',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 16,9, 52, 56),
                'updated_at' => Carbon::create(2024,4, 22,9, 52, 56),
            ],
            [
                'transaction_id' => '23697',
                'user_id' => '94795',
                'amount' => '146.97',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444796',
                'billing_id' => '333920',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,9, 57, 38),
                'updated_at' => Carbon::create(2024,4, 22,9, 57, 38),
            ],
            [
                'transaction_id' => '23698',
                'user_id' => '94798',
                'amount' => '179.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444799',
                'billing_id' => '333926',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,9, 58, 12),
                'updated_at' => Carbon::create(2024,4, 22,9, 58, 12),
            ],
            [
                'transaction_id' => '23699',
                'user_id' => '94801',
                'amount' => '180.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444802',
                'billing_id' => '333931',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,9, 58, 42),
                'updated_at' => Carbon::create(2024,4, 22,9, 58, 42),
            ],
            [
                'transaction_id' => '23700',
                'user_id' => '94804',
                'amount' => '150.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444805',
                'billing_id' => '333934',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,9, 59, 12),
                'updated_at' => Carbon::create(2024,4, 22,9, 59, 12),
            ],
            [
                'transaction_id' => '23701',
                'user_id' => '94804',
                'amount' => '81.98',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444805',
                'billing_id' => '333934',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,9, 59, 31),
                'updated_at' => Carbon::create(2024,4, 22,9, 59, 31),
            ],
            [
                'transaction_id' => '23702',
                'user_id' => '94807',
                'amount' => '29.99',
                'payment_method' => 'cash',
                'status' => 'pending',
                'card_id' => null,
                'billing_id' => '333937',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22,9, 59, 53),
                'updated_at' => Carbon::create(2024,4, 22,9, 59, 53),
            ],
            [
                'transaction_id' => '23703',
                'user_id' => '94807',
                'amount' => '70.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444808',
                'billing_id' => '333937',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 8),
                'updated_at' => Carbon::create(2024,4, 22, 10, 8),
            ],
            [
                'transaction_id' => '23704',
                'user_id' => '94810',
                'amount' => '49.99',
                'payment_method' => 'cash',
                'status' => 'pending',
                'card_id' => null,
                'billing_id' => '333940',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 34),
                'updated_at' => Carbon::create(2024,4, 22, 10, 34),
            ],[
                'transaction_id' => '23705',
                'user_id' => '94812',
                'amount' => '25.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444813',
                'billing_id' => '333942',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 1, 31),
                'updated_at' => Carbon::create(2024,4, 22, 10, 1, 31),
            ],
            [
                'transaction_id' => '23706',
                'user_id' => '94818',
                'amount' => '39.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444819',
                'billing_id' => '333948',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 3, 1),
                'updated_at' => Carbon::create(2024,4, 22, 10, 3, 1),
            ],
            [
                'transaction_id' => '23707',
                'user_id' => '94812',
                'amount' => '39.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444813',
                'billing_id' => '333942',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 1, 31),
                'updated_at' => Carbon::create(2024,4, 22, 10, 1, 31),
            ],
            [
                'transaction_id' => '23708',
                'user_id' => '94818',
                'amount' => '49.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444819',
                'billing_id' => '333948',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 3, 1),
                'updated_at' => Carbon::create(2024,4, 22, 10, 3, 1),
            ],
            [
                'transaction_id' => '23709',
                'user_id' => '94821',
                'amount' => '80.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444822',
                'billing_id' => '333951',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 4, 21),
                'updated_at' => Carbon::create(2024,4, 22, 10, 4, 21),
            ],
            [
                'transaction_id' => '23710',
                'user_id' => '94821',
                'amount' => '50.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444822',
                'billing_id' => '333951',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 4, 36),
                'updated_at' => Carbon::create(2024,4, 22, 10, 4, 36),
            ],
            [
                'transaction_id' => '23711',
                'user_id' => '94824',
                'amount' => '75.98',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444825',
                'billing_id' => '333954',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 5, 4),
                'updated_at' => Carbon::create(2024,4, 22, 10, 5, 4),
            ],
            [
                'transaction_id' => '23712',
                'user_id' => '94827',
                'amount' => '152.97',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444828',
                'billing_id' => '333957',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 5, 32),
                'updated_at' => Carbon::create(2024,4, 22, 10, 5, 32),
            ],
            [
                'transaction_id' => '23713',
                'user_id' => '94827',
                'amount' => '70.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444828',
                'billing_id' => '333957',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 5, 50),
                'updated_at' => Carbon::create(2024,4, 22, 10, 5, 50),
            ],
            [
                'transaction_id' => '23714',
                'user_id' => '94830',
                'amount' => '65.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444831',
                'billing_id' => '333960',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 6, 18),
                'updated_at' => Carbon::create(2024,4, 22, 10, 6, 18),
            ], [
                'transaction_id' => '23715',
                'user_id' => '94830',
                'amount' => '65.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444831',
                'billing_id' => '333960',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 6, 18),
                'updated_at' => Carbon::create(2024,4, 22, 10, 6, 18),
            ],
            [
                'transaction_id' => '23716',
                'user_id' => '94830',
                'amount' => '34.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444831',
                'billing_id' => '333960',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 6, 37),
                'updated_at' => Carbon::create(2024,4, 22, 10, 6, 37),
            ],
            [
                'transaction_id' => '23717',
                'user_id' => '94833',
                'amount' => '140.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444834',
                'billing_id' => '333963',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 7, 8),
                'updated_at' => Carbon::create(2024,4, 22, 10, 7, 8),
            ],
            [
                'transaction_id' => '23718',
                'user_id' => '94833',
                'amount' => '49.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444834',
                'billing_id' => '333963',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 7, 24),
                'updated_at' => Carbon::create(2024,4, 22, 10, 7, 24),
            ],
            [
                'transaction_id' => '23719',
                'user_id' => '94836',
                'amount' => '99.98',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444837',
                'billing_id' => '333966',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 7, 50),
                'updated_at' => Carbon::create(2024,4, 22, 10, 7, 50),
            ],
            [
                'transaction_id' => '23720',
                'user_id' => '94836',
                'amount' => '42.99',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444837',
                'billing_id' => '333966',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 8, 10),
                'updated_at' => Carbon::create(2024,4, 22, 10, 8, 10),
            ],
            [
                'transaction_id' => '23721',
                'user_id' => '94839',
                'amount' => '80.00',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444840',
                'billing_id' => '333969',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 8, 38),
                'updated_at' => Carbon::create(2024,4, 22, 10, 8, 38),
            ],
            [
                'transaction_id' => '23722',
                'user_id' => '94839',
                'amount' => '101.98',
                'payment_method' => 'card',
                'status' => 'completed',
                'card_id' => '444840',
                'billing_id' => '333969',
                'refunder' => null,
                'created_at' => Carbon::create(2024,4, 22, 10, 8, 54),
                'updated_at' => Carbon::create(2024,4, 22, 10, 8, 54),
            ],
        ]);
    }
}
