<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Red Rose Bouquet',
                'description' => 'A beautiful bouquet of red roses perfect for expressing love and passion.',
                'price' => 39.99,
                'quantity' => 50,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'White Lily Arrangement',
                'description' => 'An elegant arrangement of white lilies symbolizing purity and tranquility.',
                'price' => 49.99,
                'quantity' => 30,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mixed Tulip Bouquet',
                'description' => 'A colorful bouquet of mixed tulips to brighten any occasion.',
                'price' => 29.99,
                'quantity' => 40,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mixed Tulip Bouquet',
                'description' => 'A colorful bouquet of mixed tulips to brighten any occasion.',
                'price' => 29.99,
                'quantity' => 40,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sunflower Delight',
                'description' => 'A vibrant bouquet of sunflowers that bring a touch of sunshine to any room.',
                'price' => 34.99,
                'quantity' => 25,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Orchid Bliss',
                'description' => 'An exotic and elegant potted orchid that adds sophistication to any space.',
                'price' => 59.99,
                'quantity' => 20,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spring Medley',
                'description' => 'A delightful mix of seasonal flowers that encapsulate the essence of spring.',
                'price' => 42.99,
                'quantity' => 35,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Garden Basket',
                'description' => 'A beautiful basket filled with a mix of blooming plants and greenery.',
                'price' => 64.99,
                'quantity' => 15,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exotic Love',
                'description' => 'A passionate arrangement of exotic flowers perfect for an unforgettable gift.',
                'price' => 89.99,
                'quantity' => 10,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Daisy Delight',
                'description' => 'Cheerful daisies arranged in a vase to bring joy and happiness.',
                'price' => 25.99,
                'quantity' => 45,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Romantic Roses',
                'description' => 'A dozen long-stemmed roses that symbolize love, admiration, and gratitude.',
                'price' => 79.99,
                'quantity' => 20,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peony Perfection',
                'description' => 'Lush peonies that represent wealth, prosperity, and honor.',
                'price' => 70.99,
                'quantity' => 18,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Autumn Splendor',
                'description' => 'A warm and inviting bouquet that captures the essence of autumn.',
                'price' => 55.99,
                'quantity' => 25,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Succulent Garden',
                'description' => 'A diverse mix of hardy succulents that make for a perfect, low-maintenance gift.',
                'price' => 45.99,
                'quantity' => 50,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carnation Cascade',
                'description' => 'A lush cascade of colorful carnations, symbolizing fascination and distinction.',
                'price' => 30.99,
                'quantity' => 40,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elegant Iris',
                'description' => 'An elegant bouquet of irises, conveying messages of faith, hope, and wisdom.',
                'price' => 35.99,
                'quantity' => 25,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tropical Paradise',
                'description' => 'Bring the allure of a tropical paradise into your home with this vibrant and exotic arrangement.',
                'price' => 75.99,
                'quantity' => 15,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fragrant Lavender Pot',
                'description' => 'A pot of blooming lavender, known for its calming and soothing fragrance.',
                'price' => 22.99,
                'quantity' => 30,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Herb Garden Kit',
                'description' => 'Start your own herb garden with this kit, featuring basil, mint, cilantro, and more.',
                'price' => 49.99,
                'quantity' => 20,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rainbow Rose Bouquet',
                'description' => 'A stunning bouquet of roses dyed in the colors of the rainbow, symbolizing happiness and joy.',
                'price' => 65.99,
                'quantity' => 25,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bonsai Tree',
                'description' => 'A meticulously cultivated bonsai tree that embodies harmony and balance.',
                'price' => 120.99,
                'quantity' => 10,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zen Succulent Arrangement',
                'description' => 'A serene arrangement of succulents, perfect for bringing a sense of calm and mindfulness.',
                'price' => 28.99,
                'quantity' => 35,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Butterfly Garden Seed Kit',
                'description' => 'Create your own butterfly garden with this seed kit, attracting beautiful butterflies.',
                'price' => 19.99,
                'quantity' => 50,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hydrangea Heaven',
                'description' => 'A breathtaking arrangement of hydrangeas in various shades of blue and purple.',
                'price' => 60.99,
                'quantity' => 20,
                'imgUrl' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];



        DB::table('products')->insert($products);
    }
}
